permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet
gems: [jekyll-paginate]

# 作者信息
author: 
  name: 冷血誓言
  email: 438653638@qq.com
  link: CoterJiesen.github.io
  weibo: http://weibo.com/438653638
  github: http://github.com/CoterJiesen



# 站点信息
title: 冷血誓言的博客
description: My personal blog
url: CoterJiesen.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/headphto.png
favicon: /public/img/headphto.png


# disqus 设置
disqus:
  shortname: CoterJiesen

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档